// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fklszvxgafjqcytgwyva.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZrbHN6dnhnYWZqcWN5dGd3eXZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2NzYwMTcsImV4cCI6MjA2OTI1MjAxN30.0uwAce6gP_PpWi1ZEg0xv3iWi4M5AmaiAA3YkcmT3c8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});